;(function () {
  var render_query = function() {
    var text = $("#query").val();
    eval("var specs = " + text);
    if(!("layers" in specs)) {
      specs = _.flatten([specs]);
      specs = {layers: specs};
    }
    console.log(specs)
    render(specs);
  }


  var render = function(specs) {
    var ex   = function () {
      $("#examples").empty();
      return d3.select('#examples').append('span');
    };
    var guid = gg.util.Util.hashCode(JSON.stringify(specs));
    if (!specs.data) {
      specs.data = gg.data.Table.fromArray(bigdata, null, 'row')
    }
    //specs.opt = {optimize: true, guid: guid}
    var plot = gg(specs);
    plot.render(ex());
  }


  // This file contains the code to define the graphics and then
  // renders them using data randomly generated by data.js.

  $(document).ready(function() {
    $("#submit").click(render_query);
    render_query()

  });
})();

